In [200]:
import pandas as pd

### **Reading Files!-**

In [201]:
df_titanic_csv = pd.read_csv('https://github.com/pri-cd/Internship-Python-Analytics/raw/main/Datasets/Titanic.csv')
df_titanic_csv.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

#### **Exercises**
- **`header = 0`** Tells the `pd.read_html` to use the first row as the header row.

In [202]:
df_titanic_html = pd.read_html('https://github.com/pri-cd/Internship-Python-Analytics/raw/main/Datasets/Titanic.html', header=0)
df_titanic_html[0].head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,Allen,Miss. Elisabeth Walton,female,29.00,0,0,24160,211.3375,B5,S,2,NaN
1,1,1,Allison,Master. Hudson Trevor,male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN
2,1,0,Allison,Miss. Helen Loraine,female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN
3,1,0,Allison,Mr. Hudson Joshua Creighton,male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0
4,1,0,Allison,Mrs. Hudson J C (Bessie Waldo Daniels),female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN

- Reading **TXT** File

In [203]:
df_titanic_txt = pd.read_csv('https://github.com/pri-cd/Internship-Python-Analytics/raw/main/Datasets/Titanic.txt')
df_titanic_txt.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

- Read **XLSX** File

In [204]:
df_titanic_xlsx = pd.read_excel('https://github.com/pri-cd/Internship-Python-Analytics/raw/main/Datasets/Titanic.xlsx')
df_titanic_xlsx.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

- Reading **JSON** File!-

In [205]:
df_titanic_json = pd.read_json('https://github.com/pri-cd/Internship-Python-Analytics/raw/main/Datasets/Titanic.json')
df_titanic_json.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.55,C22 C26,S,11,,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,,,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,,,"Montreal, PQ / Chesterville, ON"

- Reading **Semi-Colon** Seperated File

In [206]:
df_titanic_semiColon =pd.read_csv('https://github.com/pri-cd/Internship-Python-Analytics/raw/main/Datasets/Titanic%20Semicolon.csv', sep=';')
df_titanic_semiColon.head()

,Unnamed: 0,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [207]:
del(df_titanic_csv, df_titanic_html, df_titanic_txt, df_titanic_xlsx, df_titanic_json)

### **AI, ML & Deep Learning**

#### **Basics**  
- **AI** (Artificial Intelligence) is the **superset** of Machine Learning.  
- **ML** (Machine Learning) is the **superset** of Deep Learning.  

---

#### **Supervised Learning**  
Supervised learning uses labeled data to train models, allowing them to predict outcomes based on input-output pairs.  
Examples:  
- Classification (e.g., identifying emails as spam or not)  
- Regression (e.g., predicting house prices)  

---

#### **Unsupervised Learning**  
Unsupervised learning works with **unlabeled data**. The model tries to find patterns or groupings without knowing the desired output in advance.  
Examples:  
- Clustering (e.g., customer segmentation)  
- Dimensionality Reduction (e.g., PCA for data compression)

In [208]:
df_salary = pd.read_csv('https://github.com/pri-cd/Internship-Python-Analytics/raw/main/Datasets/Salary%20Data.csv')
df_salary.head()

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [209]:
print(f"Salary --- Max: {df_salary['Salary'].max()}, Min: {df_salary['Salary'].min()}")
print(f"Experience --- Max: {df_salary['Experience Years'].max()}, Min: {df_salary['Experience Years'].min()}")

Salary --- Max: 122391, Min: 37731
Experience --- Max: 10.5, Min: 1.1

- The Salary is Too High in Comparision to Experience Years..
- I'll have to **Normalise** it or **Scale it Down**
- For, Minimum `MSE` (Mean Squared Error)

In [210]:
'''
  Simple Scaling:
    - df_salary['Salary'] = df_salary['Salary'] / 10000
'''
from sklearn.preprocessing import StandardScaler, MinMaxScaler

mmScaler = MinMaxScaler()
SScaler = StandardScaler()


df_salary['Salary'] = SScaler.fit_transform(df_salary[['Salary']])
df_salary['Experience Years'] = SScaler.fit_transform(df_salary[['Experience Years']])

df_salary.head()

   Experience Years    Salary
0         -1.540753 -1.381718
1         -1.502733 -1.247803
2         -1.464713 -1.113888
3         -1.388673 -1.444636
4         -1.198574 -1.218491

In [211]:
print(f"Columns: {df_salary.columns.tolist()}")
print(f"Shape: {df_salary.shape}")

Columns: ['Experience Years', 'Salary']
Shape: (40, 2)

## Explanation of X and Y in a Supervised Linear Regression Model

In a supervised learning model, such as **Linear Regression**, we aim to predict a dependent variable (often called the "target") based on one or more independent variables (often called "features").

### X (Independent Variable)
- **X** represents the input feature(s) of the model, also known as the **independent variable**.
- In this case, **X** is the **years of experience**.
- It is called "independent" because its values are not dependent on any other variable in the dataset.

### Y (Dependent Variable)
- **Y** represents the output of the model, also known as the **dependent variable** or the **target**.
- In this case, **Y** is the **salary**.
- It is called "dependent" because its values are dependent on the input (X), and our goal is to predict this value based on the provided features.

### In Our Example:
- **X (Experience)**: The number of years of experience someone has.
- **Y (Salary)**: The salary that is earned based on those years of experience.

In a linear regression model, we use the relationship between X and Y to create a straight line that best fits the data, allowing us to predict the salary (Y) for a given number of years of experience (X).

In [212]:
print(f"Null, NA Elements: {df_salary['Experience Years'].isna().sum()}, {df_salary['Experience Years'].isnull().sum()}")

Null, NA Elements: 0, 0

- What we have to **Predict** ? `(Y)`
- What we have to use to **Predict** Y ? `(X)`

#### **Single Square Brackets** `[]`
- **Usage**: To select a single column from a DataFrame and get it as a **pandas Series**.
- **Why**: The target variable `y` is typically used as a 1D array for machine learning models.


#### **Double Square Brackets** `[[]]`
- **Usage**: To select a single column from a DataFrame and get it as a **pandas DataFrame**.
- **Why**: The feature matrix `X` should be a 2D array, even if there's only one feature. Machine learning models **expect** the input features to be in this format.

In [213]:
y = df_salary['Salary']
x = df_salary[['Experience Years']]

print(f"Shape of Y: {y.shape} & X: {x.shape}")

Shape of Y: (40,) & X: (40, 1)

## 🧠 Quick Reference: Shape `(40, 1)` vs `(40,)` in Linear Regression

In linear regression, understanding the shape of **X** (independent variable) and **y** (dependent variable) is crucial!

### X (Independent Variable) 🛠️
- **Shape (40, 1)**:
  - This is a 2D array with 40 rows and 1 column.
  - **Why?** ✅ Machine learning models like linear regression expect input features in a 2D format.
  - 📋 **Example**:
    ```python
    X = df[['Experience Years']]  # 2D array with 40 rows, 1 column
    ```

### y (Dependent Variable) 🎯
- **Shape (40,)**:
  - This is a 1D array with 40 elements.
  - **Why?** ✅ It's fine for `y` (target) to be a 1D array because you're predicting just one value per row.
  - 📋 **Example**:
    ```python
    y = df['Salary']  # 1D array with 40 values
    ```

### 📊 Summary:
- **Use (40, 1)** for `X` (features) ✅
- **Use (40,)** for `y` (target) ✅

Remember:
- **X** should be 2D (even for one feature).
- **y** can stay 1D.

## 🧩 Train-Test Split

**Train-Test Split** is a technique used to evaluate the performance of a machine learning model. It involves dividing your dataset into two subsets: one for training the model and one for testing its performance.

### **Why Use Train-Test Split?**
- **Train the Model**: Use a portion of the data to train the model.
- **Evaluate the Model**: Use the remaining data to test how well the model performs on unseen data.

In [214]:
from sklearn.model_selection import train_test_split

# Why "random_state"?
# Because, We don't want to randomise our Train, Test Split, Everytime We Run It.
# Also, Always be ready to present & With Confidence!.
XTr, XTe, YTr, YTe = train_test_split(x, y, train_size=0.75, test_size=0.25, random_state=42)

print(f"Shape of XTr: {XTr.shape} & Xte: {XTe.shape}")
print(f"Shape of YTr: {YTr.shape} & YTe: {YTe.shape}")

XTr.head()

Shape of XTr: (30, 1) & Xte: (10, 1)
Shape of YTr: (30,) & YTe: (10,)

    Experience Years
25          0.284198
9          -0.742337
13         -0.514218
31          1.044594
34          1.348753

### **Starting Analysis**

In [215]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


# Created A Simple Instance of Linear Regression!- & Fitting!
Model = LinearRegression()
Model.fit(XTr, YTr)

# Start Prediction!
yPred = Model.predict(XTe)

In [216]:
df_results = pd.DataFrame({
    'Actual': YTe,
    'Predicted': yPred
})

df_results.head()

      Actual  Predicted
19 -0.532094  -0.216516
16 -0.694228  -0.401498
15 -0.739621  -0.401498
26  0.749252   0.338432
4  -1.218491  -1.141428

### **Checking Accuracy**
- We've done The Model Fitting & Analysis in above Cell.
- Now, We've to check the accuracy and MSE.

In [217]:
# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(YTe, yPred)

# Calculate R-squared score
r2 = r2_score(YTe, yPred)
print(f"R-squared (R²) Score: {round((r2 * 100), 4)} % Accuracy!")
print(f"Mean Squared Error: {mse}")

R-squared (R²) Score: 94.2675 % Accuracy!
Mean Squared Error: 0.06228429511646284